# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Thomas Huang
email: thomaskhuang@ucla.edu
description: >- # this means to ignore newlines until "baseurl:"
    I hope you enjoy the content, and feel free to contact me via email about anything!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://github.com/thomhuang/thomhuang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: thomaskhuang
github_username:  thomhuang
collections:
  projects:
    output: true
    collections_dir: projects
  tutorials:
    output: true
    collections_dir: tutorials
  picposts:
    output: true
    order:
        - 2021-04-04-Blog-Post-0.md
        - 2021-04-12-Blog-Post-1.md
        - 2021-04-27-Blog-Post-2.md
        - 2021-05-15-Blog-Post-3.md
    collections_dir: picposts

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
